module Jx
end

require_relative 'jx/assignment'
require_relative 'jx/compiler'
require_relative 'jx/func_call'
require_relative 'jx/function'
require_relative 'jx/ident'
require_relative 'jx/if'
require_relative 'jx/infix_call'
require_relative 'jx/integer_literal'
require_relative 'jx/package'
require_relative 'jx/parameter'
require_relative 'jx/parser'
require_relative 'jx/stmt'
require_relative 'jx/stmt_list'
require_relative 'jx/string_literal'
require_relative 'jx/transform'
require_relative 'jx/type_ref'
require_relative 'jx/var_decl'
require_relative 'jx/variable'
require_relative 'jx/while_loop'
